project:
  type: website

website:
  title: "NB"
  navbar:
    left:
      - sidebar:main-sections
      - about.qmd
      - index.qmd

    
  sidebar:
    - id: main-sections
      title: "Main Sections"
      contents: 
        - section: "Sections"
          contents:
            - math/index.qmd
            - cse/index.qmd
            - nat-sci/index.qmd
            - life-sci/index.qmd
            - finance-econ/index.qmd
            - humanities/index.qmd
            - life/index.qmd
        


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



