test_fib: test_fib.cc fib.cc fib.hh
	g++ -o test_fib test_fib.cc fib.cc
test_fib2: test_fib2.cc fib.cc
	g++ -o test_fib2 test_fib2.cc fib.cc
test_mat: test_mat.cc
	g++ -o test_mat test_mat.cc 
test_arr: arr_test.cc
	g++ -o test_arr arr_test.cc
test_mat2: test_mat2.cc mat_add.cc mat.hh
	g++ -o test_mat2 test_mat2.cc mat_add.cc
test_mult: test_mult.cc mat_mult.cc mat.hh
	g++ -o test_mult test_mult.cc mat_mult.cc mat_add.cc